### ISSUE TITLE
Allow "infinite" leveling

### ISSUE THREAD

**Issue by FluffyDiscord** [BlockCrusader/BSWLmod#3]
Right now we are limited to max level of 100. It would be nice to remove this level cap. I am aware than I can "simulate", for example, 1000 levels by adjusting the damage scaling and XP required per level, but then the damage jumps would be rather jarring, jumping up to few dozen percent per reached level, while if we had "real" 1000 levels, the damage would scale smoothly.

**Comment by BlockCrusader** [comment]
It's actually not possible to go above level 100 due to integer limits with XP. With the highest possible base XP (I don't remember what it is exactly but it's quite high; in the millions) level 100 requires roughly 2 billion XP. Seeing as the integer limit is around 2.1 billion, going any higher than level 100 would cause overflow problems for weapons given high base XP values.
Also IMO level 100 already requires enough effort to reach and grants a large enough boost for most weapons (Especially with extra boosts from the config). Despite what you might expect from a mod like this I actually want things to be as balanced as possible.
